name: GunSurvivalGames
main: com.ericlam.mc.gun.survival.games.main.GunSG
version: ${project.version}
author: Hydranapse_
depend: [ Minigames-Core, MultiConomy, CrackShotPlus ]
softdepend: [ CustomCSWeapon, PlayerCorpse ]
api-version: "1.16"
commands:
  gsg-arena:
    description: gsg arena command
  gsg-info:
    description: gsg info command