max-loaded-arenas: 3
max-items-per-chest: 4
max-items-per-tie2: 5
lobby-location:
required-players: 2
#make countdown time faster
boost-players: 4
game-time: 600
peace-time: 20
countdown-time: 60
boost-time: 30
prestart-time: 10
predeathmatch-time: 20
deathmatch-time: 300
fallback-server: gsglobby
compass-max-track: 20
reward-kills: 20
reward-wins: 50
count-down-sound: BLOCK_NOTE_BLOCK_SNARE:1:1
active-sound: BLOCK_NOTE_BLOCK_PLING:1:1

wanted-item:
  material: ROSE_BUSH
  name: "&c懸賞"
  lore:
    - "&c點擊打開懸賞選單"
  money:
    - 50.0
    - 100.0
    - 200.0
    - 300.0
    - 400.0
    - 600.0
    - 1000.0
    - 1500.0
    - 3000.0