name: GunSurvivalGames
main: com.ericlam.mc.gun.survival.games.main.GunSG
version: 0.0.7-SNAPSHOT
author: Hydranapse_
depend: [Minigames-Core, Vault, CrackShotPlus]
softdepend: [CustomCSWeapon, CorpseReborn]
api-version: "1.13"
commands:
  gsg-arena:
    description: gsg arena command